name: Tests

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target Environment'
        type: choice
        options:
          - preprod
          - staging
          - dev
        required: true
        default: 'preprod'

jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment || 'preprod' }}
    env :
      environment: ${{ github.event.inputs.environment || 'preprod' }}
    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Configuration du JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Start Checksum Node Server
        run: |
          echo "Starting Node.js Checksum Server..."
          cd checksum
          npm install
          node index.js &
          sleep 5 

      - name: Run Karate API Tests 
        run: |
          echo "Running Karate Tests on environment: ${{ github.event.inputs.environment || 'preprod' }}"
          mvn clean test \
            -Dkarate.env=${{ github.event.inputs.environment || 'preprod' }} \
            -Dkarate.options="classpath:features/Practice"
    
      - name: Cache JMeter
        id: cache-jmeter
        uses: actions/cache@v3
        with:
          path: jmeter
          key: jmeter-5.6.3

      - name: Install JMeter 5.6.3
        if: steps.cache-jmeter.outputs.cache-hit != 'true'
        run: |
          wget https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-5.6.3.tgz
          tar -xzf apache-jmeter-5.6.3.tgz
          mv apache-jmeter-5.6.3 jmeter
          rm apache-jmeter-5.6.3.tgz

      - name: Configuration de Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Installation de Taurus (bzt)
        run: |
          pip install bzt
          pip install urwid==2.1.2

      - name: Créer la configuration Taurus
        run: |
          cat <<EOF > octane_config.yml
          modules:
            jmeter:
              path: $PWD/jmeter/bin/jmeter
          reporting:
          - module: junit-xml
            filename: report_octane.xml
            data-source: sample-labels
            sample-labels: true
          settings:
            check-updates: false
          EOF

      - name: Exécuter tous les tests du dossier
        run: |
          for file in src/test/jmeter/*.jmx; do
            echo "Exécution de $file..."
            FILENAME=$(basename "$file" .jmx)
            bzt "$file" octane_config.yml -q
            sed -i -E "s/classname=\"bzt-[0-9]+\"/classname=\"$FILENAME\"/g" report_octane.xml
            mv report_octane.xml "report_${FILENAME}.xml"
          done

      - name: Sauvegarde du rapport JUnit (Artifact)
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: jmeter-test-results
          path: report_*.xml
          retention-days: 5

      - name: Sauvegarde des rapports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: surefire-reports-${{ github.event.inputs.environment || 'preprod'}}
          path: target/surefire-reports/